image: ${CI_REGISTRY}/ston-fi/docker/rust-build:20.10.24_1.84.0-c421eb08

# Prevent duplicate pipelines, branch pipeline and merge_request pipeline
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'

stages:
  - test
  - release

variables:
  FF_USE_FASTZIP: 1
  CACHE_COMPRESSION_LEVEL: "fastest"
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo"
  RUSTFLAGS: "-D warnings -C target-cpu=znver2"
  TARGET_CPU_MARCH: "znver2"

cache:
  key: shared-cache
  paths:
    - target/
    - .cargo/

test-branch:
  stage: test
  script:
    - env
    - cmake -version
    - gcc -v
    - g++ -v
    - rm -rf ton
    - cargo fmt --check
    - cargo rustc -- $RUSTFLAGS
    - cargo test --lib
  tags:
    - ston
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != 'merge_request_event'

test-mr:
  tags:
    - ston
  stage: test
  script:
    - env
    - cmake -version
    - gcc -v
    - g++ -v
    - rm -rf ton
    - cargo fmt --check
    - cargo rustc -- $RUSTFLAGS
    - cargo test --lib -- --test-threads=1
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  interruptible: true

test-mr-no-avx:
  tags:
    - ston
  stage: test
  script:
    - rm -rf ton
    - cargo build --features no_avx512
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  allow_failure: true
  interruptible: true

.test-mr-arm-m3:
  tags:
    - arm_m3
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  when: manual
  allow_failure: true
  timeout: 30 minutes
  cache:
    key: arm-m3-cache
    paths:
      - target/
      - .cargo/
  variables:
    TARGET_CPU_MARCH: ""
    RUSTFLAGS: "-D warnings"
  interruptible: true

test-mr-arm-m3:
  extends: .test-mr-arm-m3
  script:
    - clang --version
    - cargo build
  when: always

test-mr-arm-m3-no-avx:
  extends: .test-mr-arm-m3
  script:
    - clang --version
    - cargo build --features no_avx512


test-master:
  tags:
    - ston
  stage: test
  script:
    - cargo fmt --check
    - cargo rustc -- $RUSTFLAGS
    - cargo test --lib -- --test-threads=1
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

release-master:
  tags:
    - ston
  stage: release
  variables:
    GIT_STRATEGY: clone
  before_script:
    - 'git remote set-url origin https://$CI_REPOSITORY_USER:$CI_REPOSITORY_TOKEN@git.stonfi.net/$CI_PROJECT_PATH.git'
    - 'git config --global user.name "ci"'
    - 'git config --global user.email "ci@stonfi.net"'
    - 'git config push.pushOption "ci.skip"'
  script:
    - git checkout $CI_BUILD_REF_NAME
    - cargo fmt --check
    - cargo rustc -- $RUSTFLAGS
    - cargo test --lib -- --test-threads=1
    - cargo release release --execute --no-publish --no-confirm
    - export VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0]["version"]')
    - echo "Released version $VERSION"
    - export MAJOR_MINOR=$(echo $VERSION | cut -d "." -f1,2)
    - export PATCH=$(echo $VERSION | cut -d "." -f3)
    - export NEW_VERSION="$MAJOR_MINOR.$((PATCH+1))-dev"
    - echo "Starting next development iteration $NEW_VERSION"
    - cargo release $NEW_VERSION --execute --no-publish --no-confirm --no-tag
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual
