name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install libraries
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y libsodium-dev libsecp256k1-dev liblz4-dev gcc-11 g++-11

    - run: cargo fmt --check
    - run: cargo build --verbose
    - run: cargo test --lib -- --test-threads=1
